### ISSUE TITLE
Setup Superlobby for a specific world

### ISSUE THREAD

**Issue by alexander-rebello** [PedroJM96/SuperLobbyDeluxe#10]
Hi, I'm trying to setup SuperLobby specifically for one world because I want to have a lobby and a survival world on the same server. I know I could use Bungeecord, but in my case, it's not possible. So when it comes to configuration, I always set "lobby" as the world, e.g.:
```
disable-daylight-sensor-interaction:
  enable: true
  use-spawn-radius: false
  world:
  - lobby
```
I've created this lobby world with Multiverse, which worked. It created a lobby world folder and I can also teleport to that world. I also wanted the players to always be teleported to the lobby on join, so I set it up inn the spawn.yml:
```
lobby:
  world: lobby
  x: 88.5
  y: 143.0
  z: 226.5
  yaw: -90.0
  pi: 0.0
```
Now, if I join the server, first, I don't get teleported to the lobby world, and second I get this error in the console:
```
[09:16:10] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to SuperLobby v4.5.7
java.lang.IllegalArgumentException: location.world
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1254) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1199) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1194) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity.teleport(CraftEntity.java:548) ~[paper-1.19.3.jar:git-Paper-386]
	at com.pedrojm96.superlobby.SuperLobby.teleportToSpawn(SuperLobby.java:466) ~[?:?]
	at com.pedrojm96.superlobby.listener.PlayerListener.onJoinSpawn(PlayerListener.java:177) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:319) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:585) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
I hope I have described my problem in enough detail and you can help me solve it.

**Comment by alexander-rebello** [comment]
Very weird, just installed Vault and updated EssentialsX, didn't change a thing with SuperLobby, but it works again.
