### ISSUE TITLE
There is a problem running on 1.20.1

### ISSUE THREAD

**Issue by NewPixelDev** [PedroJM96/SuperLobbyDeluxe#21]
The error is as follows:

> [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
[22:15:41] [Server thread/WARN]: java.lang.NoSuchFieldException: b
[22:15:41] [Server thread/WARN]: 	at java.base/java.lang.Class.getField(Class.java:2117)
[22:15:41] [Server thread/WARN]: 	at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
[22:15:41] [Server thread/WARN]: 	at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
[22:15:41] [Server thread/WARN]: 	at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
[22:15:41] [Server thread/WARN]: 	at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
[22:15:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:15:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[22:15:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[22:15:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[22:15:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[22:15:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[22:15:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[22:15:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by PedroJM96** [comment]
Fixed in latest version
