### ISSUE TITLE
Erro in 1.21.3:

### ISSUE THREAD

**Issue by thiagogebrimm** [PedroJM96/SuperLobbyDeluxe#40]
```
[09:06:33] [Server thread/INFO]: [SuperLobby] Enabling SuperLobby v4.7.6
[09:06:33] [Server thread/INFO]: -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[09:06:33] [Server thread/INFO]: [SuperLobby]    _____                       _           _     _           
[09:06:33] [Server thread/INFO]: [SuperLobby]   / ____|                     | |         | |   | |          
[09:06:33] [Server thread/INFO]: [SuperLobby]  | (___  _   _ _ __   ___ _ __| |     ___ | |__ | |__  _   _ 
[09:06:33] [Server thread/INFO]: [SuperLobby]   \___ \| | | | '_ \ / _ \ '__| |    / _ \| '_ \| '_ \| | | |
[09:06:33] [Server thread/INFO]: [SuperLobby]   ____) | |_| | |_) |  __/ |  | |___| (_) | |_) | |_) | |_| |
[09:06:33] [Server thread/INFO]: [SuperLobby]  |_____/ \__,_| .__/ \___|_|  |______\___/|_.__/|_.__/ \__, |
[09:06:33] [Server thread/INFO]: [SuperLobby]               | |                                       __/ |
[09:06:33] [Server thread/INFO]: [SuperLobby]               |_|                                      |___/ 
[09:06:33] [Server thread/INFO]: [SuperLobby]     
[09:06:33] [Server thread/INFO]: -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[09:06:33] [Server thread/INFO]: [SuperLobby] Deluxe Version: V4.7.6
[09:06:33] [Server thread/INFO]: [SuperLobby] Plugin Create by PedroJM96.
[09:06:33] [Server thread/INFO]: [SuperLobby] Loading Libraries...
[09:06:33] [Server thread/INFO]: [SuperLobby] Loading library commons-lang-commons-lang-2.6
[09:06:33] [Server thread/INFO]: [SuperLobby] commons-lang-commons-lang-2.6 library loaded successfully.
[09:06:33] [Server thread/INFO]: [SuperLobby] Loading library commons-codec-commons-codec-1.15
[09:06:33] [Server thread/INFO]: [SuperLobby] commons-codec-commons-codec-1.15 library loaded successfully.
[09:06:33] [Server thread/INFO]: [SuperLobby] Loading library com.google.code.gson-gson-2.9.0
[09:06:33] [Server thread/INFO]: [SuperLobby] com.google.code.gson-gson-2.9.0 library loaded successfully.
[09:06:34] [Server thread/INFO]: [SuperLobby] Loading configuration...
[09:06:34] [Server thread/INFO]: [SuperLobby] Load config.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] config.yml loaded.
[09:06:34] [Server thread/INFO]: [SuperLobby] Load messages_EN.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] messages_EN.yml loaded.
[09:06:34] [Server thread/INFO]: [SuperLobby] Load spawn.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] spawn.yml loaded.
[09:06:34] [Server thread/INFO]: [SuperLobby] Load chat.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] chat.yml loaded.
[09:06:34] [Server thread/INFO]: [SuperLobby] Load infocommands.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] infocommands.yml loaded.
[09:06:34] [Server thread/INFO]: [SuperLobby] Register info command /info
[09:06:34] [Server thread/INFO]: [SuperLobby] Register info command /youtubers
[09:06:34] [Server thread/INFO]: [SuperLobby] Register info command /socialpages
[09:06:34] [Server thread/INFO]: [SuperLobby] Register info command /discord
[09:06:34] [Server thread/INFO]: [SuperLobby] Register info command /regras
[09:06:34] [Server thread/INFO]: [SuperLobby] Register info command /help
[09:06:34] [Server thread/INFO]: [SuperLobby] Load customevents.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] customevents.yml loaded.
[09:06:34] [Server thread/INFO]: [SuperLobby] Load items.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] items.yml loaded.
[09:06:34] [Server thread/INFO]: [SuperLobby] Load menus.yml
[09:06:34] [Server thread/INFO]: [SuperLobby] menus.yml loaded.
[09:06:34] [Server thread/ERROR]: Error occurred while enabling SuperLobby v4.7.6 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be InterfaceMethodref constant
	at com.pedrojm96.superlobby.inventory.menu.CoreMenu.setSound(CoreMenu.java:237) ~[?:?]
	at com.pedrojm96.superlobby.SuperLobby.loadMenus(SuperLobby.java:540) ~[?:?]
	at com.pedrojm96.superlobby.SuperLobby.onEnable(SuperLobby.java:206) ~[?:?]
	at SuperLobbyDeluxe-4.7.6-shaded.jar/com.pedrojm96.superlobby.SuperLobbyLoader.onEnable(SuperLobbyLoader.java:34) ~[SuperLobbyDeluxe-4.7.6-shaded.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:657) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:606) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:770) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:532) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:360) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1248) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:342) ~[purpur-1.21.3.jar:1.21.3-2337-ca668ab]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[09:06:34] [Server thread/INFO]: [SuperLobby] Disabling SuperLobby v4.7.6
```

**Comment by F0RB1DD3NScripts** [comment]
same

**Comment by klmngit** [comment]
Yep, same here: 
[...]
[09:23:38 INFO]: [SuperLobby] menus.yml  create.
[09:23:38 ERROR]: Error occurred while enabling SuperLobby v4.7.6 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be InterfaceMethodref constant
[...]

**Comment by Brasil150** [comment]
Hi, any update on this issue? I am also getting this error.

**Comment by thiagogebrimm** [comment]
same erro in 1.21.4 :(

**Comment by neviskcubo** [comment]
Do you know any other good lobbying system? this one was apparently abandoned

**Comment by Brasil150** [comment]
> same erro in 1.21.4 :(

The best alternative is to try to contact him on another place.

I've tried it on YouTube, Spigot and now on Github. It always appears when there's an update in Minecraft. It's really bad to be without this plugin, my entire server depends on it.

**Comment by Brasil150** [comment]
@PedroJM96

**Comment by MassiveLag** [comment]
Please add 1.21.3+ support!

**Comment by Brasil150** [comment]
Hello everyone! A Spigot user managed to find a workaround for this issue for now! Thanks to him.
https://www.spigotmc.org/threads/%E2%9C%AA-superlobbydeluxe-1-8-8-1-21-x-%E2%9C%AA.132949/page-59#post-4816703
